"""change columns in message table

Revision ID: d2faeb7a9974
Revises: 1736d2c14e50
Create Date: 2024-12-25 10:37:34.538836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2faeb7a9974'
down_revision: Union[str, None] = '1736d2c14e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('free_qr', sa.Boolean(), nullable=False))
    op.drop_column('message', 'payment_link')
    op.drop_column('message', 'qr_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('qr_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('payment_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('message', 'free_qr')
    # ### end Alembic commands ###
